--3) Dada uma nacionalidade de um fundador, deseja-se saber:
--3.1- Os nomes, endereços e cidades que possuem museus e igrejas fundados por nativos daquela nação;
SELECT * FROM FUNDADOR
SELECT * FROM MUSEU
SELECT * FROM PONTO_TURISTICO;
SELECT * FROM ENDERECO

SELECT F.NOME [NOME FUNDADOR], E.RUA, C.NOME AS [NOME CIDADE] FROM PONTO_TURISTICO PT
INNER JOIN MUSEU M ON (PT.CODIGO_PONTO_TURISTICO=M.CODIGO_MUSEU)
INNER JOIN ENDERECO E ON (E.CODIGO_ENDERECO=PT.ID_ENDERECO)
INNER JOIN CIDADE C ON (C.CODIGO_CIDADE= E.ID_CIDADE)
INNER JOIN FUNDADOR F ON (F.CODIGO_FUNDADOR = M.ID_FUNDADOR) WHERE F.NACIONALIDADE='NACIONALIDADE 03'

SELECT F.NOME [NOME FUNDADOR], E.RUA, C.NOME AS [NOME CIDADE] FROM PONTO_TURISTICO PT
INNER JOIN IGREJA I ON (PT.CODIGO_PONTO_TURISTICO=I.CODIGO_IGREJA)
INNER JOIN ENDERECO E ON (E.CODIGO_ENDERECO=PT.ID_ENDERECO)
INNER JOIN CIDADE C ON (C.CODIGO_CIDADE= E.ID_CIDADE)
INNER JOIN FUNDADOR F ON (F.CODIGO_FUNDADOR = I.ID_FUNDADOR) WHERE F.NACIONALIDADE<>'NACIONALIDADE 00'

--3.2- Qual(is) a(s) cidade(s) que possue(m) museus e igrejas fundados mais recentemente por daquela nação com uma população entre X e Y habitantes;
SELECT * FROM CIDADE
SELECT C.NOME AS [CIDADE] FROM ENDERECO E
INNER JOIN CIDADE C ON (C.CODIGO_CIDADE=E.ID_CIDADE)
INNER JOIN PONTO_TURISTICO PT ON (PT.ID_ENDERECO=E.CODIGO_ENDERECO)
INNER JOIN MUSEU M ON (M.CODIGO_MUSEU=PT.CODIGO_PONTO_TURISTICO) WHERE C.POPULACAO>20000 AND C.POPULACAO<100000

SELECT C.NOME AS [CIDADE] FROM ENDERECO E
INNER JOIN CIDADE C ON (C.CODIGO_CIDADE=E.ID_CIDADE)
INNER JOIN PONTO_TURISTICO PT ON (PT.ID_ENDERECO=E.CODIGO_ENDERECO)
INNER JOIN IGREJA I ON (I.CODIGO_IGREJA=PT.CODIGO_PONTO_TURISTICO) WHERE C.POPULACAO<2000000 AND C.POPULACAO>=1000000

--3.3- Quais as igrejas de certo estilo (p. ex.: “Art Nouveau”) fundadas por nativos daquela nação em um determinado período (p. ex: Século XIX).
SELECT * FROM IGREJA
SELECT I.NOME FROM FUNDADOR F
INNER JOIN IGREJA I ON (I.ID_FUNDADOR=F.CODIGO_FUNDADOR) WHERE I.ESTILO='BARROCO' AND YEAR(I.DATA_CONSTRUCAO)= 1678