--1) Dado o nome de uma cidade, deseja-se saber:

SELECT * FROM [CIDADE];
SELECT * FROM [PONTO_TURISTICO];


--PONTO TURISTICO DA CIDADE
SELECT [TIPO_PONTO_TURISTICO], [ID_ENDERECO] FROM [PONTO_TURISTICO] PT
INNER JOIN [CIDADE] C ON C.CODIGO_CIDADE=PT.[ID_CIDADE] WHERE  NOME ='CIDADE 02'

--1.1- Quais os pontos turísticos e seus endereços;
SELECT [TIPO_PONTO_TURISTICO], [ID_ENDERECO],E.RUA,E.NUMERO,E.BAIRRO,E.CEP,C.NOME,C.ESTADO FROM [PONTO_TURISTICO] PT
INNER JOIN ENDERECO E ON (E.CODIGO_ENDERECO=PT.ID_ENDERECO)
INNER JOIN [CIDADE] C ON C.CODIGO_CIDADE=PT.[ID_CIDADE] WHERE  C.NOME ='CIDADE 00' 


--1.2- Quais as igrejas e museus com fundadores nacionais;
SELECT * FROM FUNDADOR
SELECT * FROM MUSEU
SELECT * FROM PONTO_TURISTICO

SELECT [TIPO_PONTO_TURISTICO], I.NOME AS IGREJA, F.NOME AS FUNDADOR FROM [PONTO_TURISTICO] PT
INNER JOIN IGREJA I ON (I.CODIGO_IGREJA=PT.CODIGO_PONTO_TURISTICO)
INNER JOIN FUNDADOR F ON (F.CODIGO_FUNDADOR=I.ID_FUNDADOR)
INNER JOIN [CIDADE] C ON C.CODIGO_CIDADE=PT.[ID_CIDADE] WHERE  F.NACIONALIDADE='NACIONALIDADE 03' 

SELECT [TIPO_PONTO_TURISTICO], M.NOME AS MUSEU, F.NOME AS FUNDADOR FROM [PONTO_TURISTICO] PT
INNER JOIN MUSEU M ON (M.CODIGO_MUSEU=PT.CODIGO_PONTO_TURISTICO)
INNER JOIN FUNDADOR F ON (F.CODIGO_FUNDADOR=M.ID_FUNDADOR)
INNER JOIN [CIDADE] C ON C.CODIGO_CIDADE=PT.[ID_CIDADE] WHERE  F.NACIONALIDADE='NACIONALIDADE 03' AND C.NOME = 'CIDADE 03' 

--1.3- Quais são as casas de show que estão abertas em um determinado dia da semana funcionando
SELECT * FROM CASA_SHOW;
SELECT * FROM CIDADE;
SELECT * FROM PONTO_TURISTICO

SELECT NOME FROM CASA_SHOW WHERE DIA_FECHAMENTO = 'SEGUNDA FEIRA'
SELECT * FROM CASA_SHOW WHERE DIA_FECHAMENTO <> 'TERCA FEIRA'

SELECT CS.NOME FROM CASA_SHOW CS
INNER JOIN [PONTO_TURISTICO] PT ON (CS.CODIGO_CASA_SHOW=PT.CODIGO_PONTO_TURISTICO)
INNER JOIN [CIDADE] C ON C.CODIGO_CIDADE=PT.[ID_CIDADE] WHERE  C.NOME= 'CIDADE 02'  AND CS.DIA_FECHAMENTO <> 'TERCA FEIRA'


