CREATE TABLE [CIDADE](
	[CODIGO_CIDADE] INT IDENTITY(1,1) NOT NULL,
	[NOME] VARCHAR(50) NOT NULL,
	[POPULACAO] INT NOT NULL,
	[ESTADO] VARCHAR(50) NOT NULL,
	CONSTRAINT [PK_CIDADE] PRIMARY KEY CLUSTERED ([CODIGO_CIDADE])
);
CREATE TABLE [HOTEL](
	[CODIGO_HOTEL] INT IDENTITY(1,1) NOT NULL,
	[NOME] VARCHAR(50) NOT NULL,
	[ID_ENDERECO] INT NOT NULL,
	[ID_RESTAURANTE] INT NOT NULL,
	[ID_QUANT_QUARTOS] INT NOT NULL,
	[ID_CIDADE] INT NOT NULL,
	[CATEGORIA] VARCHAR(50) NOT NULL,
	CONSTRAINT [PK_HOTEL] PRIMARY KEY CLUSTERED ([CODIGO_HOTEL]),
	CONSTRAINT [FK_HOTEL_CIDADE] FOREIGN KEY ([ID_CIDADE]) REFERENCES [CIDADE] ([CODIGO_CIDADE])
);

CREATE TABLE [ENDERECO](
	[CODIGO_ENDERECO] INT IDENTITY(1,1) NOT NULL,
	[ID_CIDADE] INT NOT NULL,
	[CEP] INT NOT NULL,
	[TIPO] VARCHAR(50) NOT NULL,
	[LOGRADOURO] VARCHAR(50) NOT NULL,
	[COMPLEMENTO] VARCHAR(50) NOT NULL,
	[NUMERO] INT NOT NULL,
	[RUA] VARCHAR(50) NOT NULL,
	[BAIRRO] VARCHAR(50) NOT NULL,
	CONSTRAINT [PK_ENDERECO] PRIMARY KEY CLUSTERED ([CODIGO_ENDERECO]),
	CONSTRAINT [FK_ENDERECO_CIDADE] FOREIGN KEY ([ID_CIDADE]) REFERENCES [CIDADE] ([CODIGO_CIDADE]),
);

CREATE TABLE [QUARTO](
	[CODIGO_QUARTO] INT IDENTITY(1,1) NOT NULL,
	[ID_HOTEL] INT NOT NULL,
	[TIPO_QUARTO] VARCHAR(50) NOT NULL,
	[NUMERO_QUARTO] INT NOT NULL,
	[DIARIA] INT NOT NULL,
	CONSTRAINT [PK_QUARTO] PRIMARY KEY CLUSTERED ([CODIGO_QUARTO]),
	CONSTRAINT [FK_QUARTO_HOTEL] FOREIGN KEY ([ID_HOTEL]) REFERENCES [HOTEL] ([CODIGO_HOTEL]),
);

CREATE TABLE [QUANTIDADE_QUARTOS](
	[CODIGO_QUANT_QUARTOS] INT IDENTITY(1,1) NOT NULL,
	[ID_HOTEL] INT NOT NULL,
	[COMUM] INT NOT NULL,
	[MEDIANO] INT NOT NULL,
	[LUXO] INT NOT NULL,
	[SUPER_LUXO] INT NOT NULL,
	[MASTER] INT NOT NULL,
	[STANDART] INT NOT NULL,
	CONSTRAINT [PK_QUANTIDA_DE_QUARTOS] PRIMARY KEY CLUSTERED ([CODIGO_QUANT_QUARTOS]),
	CONSTRAINT [FK_QUANTIDADEQUARTOS_HOTEL] FOREIGN KEY ([ID_HOTEL]) REFERENCES [HOTEL] ([CODIGO_HOTEL]),
);

CREATE TABLE [PONTOS_TURISTICOS](
	[CODIGO_PONTO_TURISTICO] INT IDENTITY(1,1) NOT NULL,
	[ID_CIDADE] INT NOT NULL,
	[ID_ENDERECO] INT NOT NULL,
	[TELEFONE] VARCHAR(50) NOT NULL,
	[DESCRICAO] VARCHAR(50) NOT NULL,
	[TIPO_PONTO_TURISTICO] VARCHAR(50) NOT NULL,
	CONSTRAINT [PK_PONTO_TURISTICO] PRIMARY KEY CLUSTERED ([CODIGO_PONTO_TURISTICO]),
	CONSTRAINT [FK_PONTO_TURISTICO_CIDADE] FOREIGN KEY ([ID_CIDADE]) REFERENCES [CIDADE] ([CODIGO_CIDADE]),
	CONSTRAINT [FK_PONTO_TURISTICO_ENDERECO] FOREIGN KEY ([ID_ENDERECO]) REFERENCES [ENDERECO] ([CODIGO_ENDERECO]),
);


