CREATE TABLE [CIDADE](
	[CODIGO_CIDADE] INT IDENTITY(1,1) NOT NULL,
	[NOME] VARCHAR(50) NOT NULL,
	[POPULACAO] INT NOT NULL,
	[ESTADO] VARCHAR(50) NOT NULL,
	CONSTRAINT [PK_CIDADE] PRIMARY KEY CLUSTERED ([CODIGO_CIDADE])
);
CREATE TABLE [RESTAURANTE](
	[CODIGO_RESTAURANTE] INT IDENTITY(1,1) NOT NULL,
	[NOME] VARCHAR(50) NOT NULL,
	[CATEGORIA] VARCHAR(50) NOT NULL,
	[ESPECIALIDADE] VARCHAR(50) NOT NULL,
	[PRECO_MEDIO] FLOAT NOT NULL,
	CONSTRAINT [PK_RESTAURANTE] PRIMARY KEY CLUSTERED ([CODIGO_RESTAURANTE]),	
);
CREATE TABLE [ENDERECO](
	[CODIGO_ENDERECO] INT IDENTITY(1,1) NOT NULL,
	[ID_CIDADE] INT NOT NULL,
	[CEP] INT NOT NULL,
	[TIPO] VARCHAR(50) NOT NULL,
	[LOGRADOURO] VARCHAR(50) NOT NULL,
	[COMPLEMENTO] VARCHAR(50) NOT NULL,
	[NUMERO] INT NOT NULL,
	[RUA] VARCHAR(50) NOT NULL,
	[BAIRRO] VARCHAR(50) NOT NULL,
	CONSTRAINT [PK_ENDERECO] PRIMARY KEY CLUSTERED ([CODIGO_ENDERECO]),
	CONSTRAINT [FK_ENDERECO_CIDADE] FOREIGN KEY ([ID_CIDADE]) REFERENCES [CIDADE] ([CODIGO_CIDADE]),
);

CREATE TABLE [HOTEL](
	[CODIGO_HOTEL] INT IDENTITY(1,1) NOT NULL,
	[NOME] VARCHAR(50) NOT NULL,
	[ID_ENDERECO] INT NOT NULL,
	[ID_RESTAURANTE] INT NOT NULL,
	[CATEGORIA] VARCHAR(50) NOT NULL,
	CONSTRAINT [PK_HOTEL] PRIMARY KEY CLUSTERED ([CODIGO_HOTEL]),
	CONSTRAINT [FK_HOTEL_ENDERECO] FOREIGN KEY ([ID_ENDERECO]) REFERENCES [ENDERECO] ([CODIGO_ENDERECO]),
	CONSTRAINT [FK_HOTEL_RESTAURANTE] FOREIGN KEY ([ID_RESTAURANTE]) REFERENCES [RESTAURANTE] ([CODIGO_RESTAURANTE]),
);


CREATE TABLE [QUARTO](
	[CODIGO_QUARTO] INT IDENTITY(1,1) NOT NULL,
	[ID_HOTEL] INT NOT NULL,
	[TIPO_QUARTO] VARCHAR(50) NOT NULL,
	[NUMERO_QUARTO] INT NOT NULL,
	[DIARIA] INT NOT NULL,
	CONSTRAINT [PK_QUARTO] PRIMARY KEY CLUSTERED ([CODIGO_QUARTO]),
	CONSTRAINT [FK_QUARTO_HOTEL] FOREIGN KEY ([ID_HOTEL]) REFERENCES [HOTEL] ([CODIGO_HOTEL]),
);

CREATE TABLE [QUANTIDADE_QUARTOS](
	[ID_HOTEL] INT NOT NULL,
	[COMUM] INT NOT NULL,
	[MEDIANO] INT NOT NULL,
	[LUXO] INT NOT NULL,
	[SUPER_LUXO] INT NOT NULL,
	[MASTER] INT NOT NULL,
	[STANDART] INT NOT NULL,
	CONSTRAINT [FK_QUANTIDADEQUARTOS_HOTEL] FOREIGN KEY ([ID_HOTEL]) REFERENCES [HOTEL] ([CODIGO_HOTEL]),
);

CREATE TABLE [PONTO_TURISTICO](
	[CODIGO_PONTO_TURISTICO] INT IDENTITY(1,1) NOT NULL,
	[ID_CIDADE] INT NOT NULL,
	[ID_ENDERECO] INT NOT NULL,
	[TELEFONE] VARCHAR(50) NOT NULL,
	[DESCRICAO] VARCHAR(50) NOT NULL,
	[TIPO_PONTO_TURISTICO] VARCHAR(50) NOT NULL,
	CONSTRAINT [PK_PONTO_TURISTICO] PRIMARY KEY CLUSTERED ([CODIGO_PONTO_TURISTICO]),
	CONSTRAINT [FK_PONTO_TURISTICO_CIDADE] FOREIGN KEY ([ID_CIDADE]) REFERENCES [CIDADE] ([CODIGO_CIDADE]),
	CONSTRAINT [FK_PONTO_TURISTICO_ENDERECO] FOREIGN KEY ([ID_ENDERECO]) REFERENCES [ENDERECO] ([CODIGO_ENDERECO]),
);

CREATE TABLE [FUNDADOR](
	[CODIGO_FUNDADOR] INT IDENTITY(1,1) NOT NULL,
	[NOME] VARCHAR(50) NOT NULL,
	[NACIONALIDADE] VARCHAR(50) NOT NULL,
	[PROFISSAO] VARCHAR(50) NOT NULL,
	[DATA_NASCIMENTO] DATE NOT NULL,
	[DATA_MORTE] DATE NOT NULL,
	CONSTRAINT [PK_FUNDADOR] PRIMARY KEY CLUSTERED ([CODIGO_FUNDADOR]),
);
CREATE TABLE [IGREJA](
	[CODIGO_IGREJA] INT NOT NULL,
	[ID_FUNDADOR] INT NOT NULL,
	[ESTILO] VARCHAR(50) NOT NULL,
	[DATA_CONSTRUCAO] DATE NOT NULL,
	[NOME] VARCHAR(50) NOT NULL,
	CONSTRAINT [FK_IGREJA_PONTO_TURISTICO] FOREIGN KEY ([CODIGO_IGREJA]) REFERENCES [PONTO_TURISTICO] ([CODIGO_PONTO_TURISTICO]),
	CONSTRAINT [FK_IGREJA_FUNDADOR] FOREIGN KEY ([ID_FUNDADOR]) REFERENCES [FUNDADOR] ([CODIGO_FUNDADOR]),
);

CREATE TABLE [MUSEU](
	[CODIGO_MUSEU] INT NOT NULL,
	[ID_FUNDADOR] INT NOT NULL,
	[NOME] VARCHAR(50) NOT NULL,
	[DATA_FUNDACAO] DATE NOT NULL,
	[VALOR_ENTRADA] FLOAT NOT NULL,
	CONSTRAINT [FK_MUSEU_PONTO_TURISTICO] FOREIGN KEY ([CODIGO_MUSEU]) REFERENCES [PONTO_TURISTICO] ([CODIGO_PONTO_TURISTICO]),
	CONSTRAINT [FK_MUSEU_FUNDADOR] FOREIGN KEY ([ID_FUNDADOR]) REFERENCES [FUNDADOR] ([CODIGO_FUNDADOR]),
);

CREATE TABLE [CASA_SHOW](
	[CODIGO_CASA_SHOW] INT NOT NULL,
	[ID_RESTAURANTE] INT NOT NULL,
	[DIA_FECHAMENTO] VARCHAR(50) NOT NULL,
	[NOME] VARCHAR(50) NOT NULL,
	CONSTRAINT [FK_CASA_SHOW_PONTO_TURISTICO] FOREIGN KEY ([CODIGO_CASA_SHOW]) REFERENCES [PONTO_TURISTICO] ([CODIGO_PONTO_TURISTICO]),
	CONSTRAINT [FK_CASA_SH0W_RESTAURANTE] FOREIGN KEY ([ID_RESTAURANTE]) REFERENCES [RESTAURANTE] ([CODIGO_RESTAURANTE]),
);




